export var homePageMock = {

  "success": true,
  "message": "",
  "resultCode": "10000",
  "body": {
    "queues": [
      {
        "manCount": "0",
        "queueNo": "2",
        "currentNo": "",
        "roomName": "",
        "position": "B区东门门诊大楼3层北区",
        "deptName": "门诊针灸推拿康复科是个坑啊大家别去，医院现在去不得啊",
        "doctName": "赵婧宇",
        "patientName": null,
        "timeStart": null,
        "timeEnd": null,
        "regId": null,
        "headImg": null,
        "patientId": 0,
        "setPatientId": false,
        "setTimeStart": false,
        "setTimeEnd": false,
        "setRegId": false,
        "setHeadImg": false,
        "setPatientName": false,
        "setCurrentNo": true,
        "setManCount": true,
        "setRoomName": true,
        "setPosition": true,
        "setQueueNo": true,
        "setDoctName": true,
        "setDeptName": true
      },
      {
        "manCount": "5",
        "queueNo": "14",
        "currentNo": "",
        "roomName": "",
        "position": "B区东门门诊大楼4层北区",
        "deptName": "邪门歪道科室",
        "doctName": "项少龙",
        "patientName": null,
        "timeStart": null,
        "timeEnd": null,
        "regId": null,
        "headImg": null,
        "patientId": 0,
        "setPatientId": false,
        "setTimeStart": false,
        "setTimeEnd": false,
        "setRegId": false,
        "setHeadImg": false,
        "setPatientName": false,
        "setCurrentNo": true,
        "setManCount": true,
        "setRoomName": true,
        "setPosition": true,
        "setQueueNo": true,
        "setDoctName": true,
        "setDeptName": true
      },
      {
        "manCount": "18",
        "queueNo": "28",
        "currentNo": "",
        "roomName": "",
        "position": "B区东门门诊大楼5层北区",
        "deptName": "赵国公主",
        "doctName": "赵倩",
        "patientName": null,
        "timeStart": null,
        "timeEnd": null,
        "regId": null,
        "headImg": null,
        "patientId": 0,
        "setPatientId": false,
        "setTimeStart": false,
        "setTimeEnd": false,
        "setRegId": false,
        "setHeadImg": false,
        "setPatientName": false,
        "setCurrentNo": true,
        "setManCount": true,
        "setRoomName": true,
        "setPosition": true,
        "setQueueNo": true,
        "setDoctName": true,
        "setDeptName": true
      }
    ],
    "appoints": null,
    "setQueues": true,
    "setAppoints": false
  }
};

